# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_HMP_CHANNEL.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HMP_CHANNEL(object):
    def setupUi(self, HMP_CHANNEL):
        HMP_CHANNEL.setObjectName("HMP_CHANNEL")
        HMP_CHANNEL.resize(450, 100)
        self.pbOnOff = QtWidgets.QToolButton(HMP_CHANNEL)
        self.pbOnOff.setGeometry(QtCore.QRect(380, 9, 60, 81))
        self.pbOnOff.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pbOnOff.setStatusTip("")
        self.pbOnOff.setAutoFillBackground(True)
        self.pbOnOff.setStyleSheet("")
        self.pbOnOff.setCheckable(True)
        self.pbOnOff.setObjectName("pbOnOff")
        self.lbCh = QtWidgets.QLabel(HMP_CHANNEL)
        self.lbCh.setGeometry(QtCore.QRect(5, 10, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lbCh.setFont(font)
        self.lbCh.setObjectName("lbCh")
        self.Volt = QtWidgets.QSplitter(HMP_CHANNEL)
        self.Volt.setGeometry(QtCore.QRect(90, 10, 112, 71))
        self.Volt.setOrientation(QtCore.Qt.Vertical)
        self.Volt.setObjectName("Volt")
        self.lblVmax = QtWidgets.QLabel(self.Volt)
        self.lblVmax.setMaximumSize(QtCore.QSize(112, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblVmax.setFont(font)
        self.lblVmax.setObjectName("lblVmax")
        self.lcdVoltage = QtWidgets.QLCDNumber(self.Volt)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lcdVoltage.setFont(font)
        self.lcdVoltage.setAutoFillBackground(True)
        self.lcdVoltage.setStyleSheet("")
        self.lcdVoltage.setSmallDecimalPoint(False)
        self.lcdVoltage.setDigitCount(5)
        self.lcdVoltage.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdVoltage.setObjectName("lcdVoltage")
        self.Current = QtWidgets.QSplitter(HMP_CHANNEL)
        self.Current.setGeometry(QtCore.QRect(230, 10, 112, 71))
        self.Current.setOrientation(QtCore.Qt.Vertical)
        self.Current.setObjectName("Current")
        self.lblImax = QtWidgets.QLabel(self.Current)
        self.lblImax.setMaximumSize(QtCore.QSize(112, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblImax.setFont(font)
        self.lblImax.setObjectName("lblImax")
        self.lcdCurrent = QtWidgets.QLCDNumber(self.Current)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdCurrent.sizePolicy().hasHeightForWidth())
        self.lcdCurrent.setSizePolicy(sizePolicy)
        self.lcdCurrent.setSmallDecimalPoint(False)
        self.lcdCurrent.setDigitCount(5)
        self.lcdCurrent.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdCurrent.setObjectName("lcdCurrent")

        self.retranslateUi(HMP_CHANNEL)
        QtCore.QMetaObject.connectSlotsByName(HMP_CHANNEL)

    def retranslateUi(self, HMP_CHANNEL):
        _translate = QtCore.QCoreApplication.translate
        HMP_CHANNEL.setWindowTitle(_translate("HMP_CHANNEL", "Form"))
        self.pbOnOff.setText(_translate("HMP_CHANNEL", "ON/OFF"))
        self.lbCh.setText(_translate("HMP_CHANNEL", "CH X"))
        self.lblVmax.setText(_translate("HMP_CHANNEL", "V_max: "))
        self.lblImax.setText(_translate("HMP_CHANNEL", "I_max: "))
