# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_save.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frSave(object):
    def setupUi(self, frSave):
        frSave.setObjectName("frSave")
        frSave.resize(113, 220)
        self.splitter_2 = QtWidgets.QSplitter(frSave)
        self.splitter_2.setGeometry(QtCore.QRect(10, 5, 91, 200))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.pbPrint = QtWidgets.QPushButton(self.splitter_2)
        self.pbPrint.setObjectName("pbPrint")
        self.pbSave = QtWidgets.QPushButton(self.splitter_2)
        self.pbSave.setObjectName("pbSave")
        self.pbLink = QtWidgets.QPushButton(self.splitter_2)
        self.pbLink.setObjectName("pbLink")

        self.retranslateUi(frSave)
        QtCore.QMetaObject.connectSlotsByName(frSave)

    def retranslateUi(self, frSave):
        _translate = QtCore.QCoreApplication.translate
        frSave.setWindowTitle(_translate("frSave", "Frame"))
        self.pbPrint.setText(_translate("frSave", "Print"))
        self.pbSave.setText(_translate("frSave", "Save"))
        self.pbLink.setText(_translate("frSave", "Link"))
