# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_hmp_LDO.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frHMP(object):
    def setupUi(self, frHMP):
        frHMP.setObjectName("frHMP")
        frHMP.resize(450, 220)
        self.layoutWidget = QtWidgets.QWidget(frHMP)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 450, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gbCH_1 = QtWidgets.QGroupBox(self.layoutWidget)
        self.gbCH_1.setStatusTip("")
        self.gbCH_1.setObjectName("gbCH_1")
        self.lcdFEB_1_volt = QtWidgets.QLCDNumber(self.gbCH_1)
        self.lcdFEB_1_volt.setGeometry(QtCore.QRect(5, 50, 210, 31))
        font = QtGui.QFont()
        font.setBold(False)
        self.lcdFEB_1_volt.setFont(font)
        self.lcdFEB_1_volt.setAutoFillBackground(True)
        self.lcdFEB_1_volt.setStyleSheet("")
        self.lcdFEB_1_volt.setObjectName("lcdFEB_1_volt")
        self.lcdFEB_1_curr = QtWidgets.QLCDNumber(self.gbCH_1)
        self.lcdFEB_1_curr.setGeometry(QtCore.QRect(5, 120, 210, 31))
        self.lcdFEB_1_curr.setDigitCount(6)
        self.lcdFEB_1_curr.setObjectName("lcdFEB_1_curr")
        self.lblFEB_V1 = QtWidgets.QLabel(self.gbCH_1)
        self.lblFEB_V1.setGeometry(QtCore.QRect(5, 30, 100, 18))
        self.lblFEB_V1.setObjectName("lblFEB_V1")
        self.lblFEB_A1 = QtWidgets.QLabel(self.gbCH_1)
        self.lblFEB_A1.setGeometry(QtCore.QRect(5, 100, 100, 18))
        self.lblFEB_A1.setObjectName("lblFEB_A1")
        self.pbCH_1 = QtWidgets.QToolButton(self.gbCH_1)
        self.pbCH_1.setGeometry(QtCore.QRect(10, 170, 201, 30))
        self.pbCH_1.setStatusTip("")
        self.pbCH_1.setCheckable(True)
        self.pbCH_1.setObjectName("pbCH_1")
        self.horizontalLayout.addWidget(self.gbCH_1)
        self.gbCH_2 = QtWidgets.QGroupBox(self.layoutWidget)
        self.gbCH_2.setStatusTip("")
        self.gbCH_2.setObjectName("gbCH_2")
        self.lcdFEB_2_volt = QtWidgets.QLCDNumber(self.gbCH_2)
        self.lcdFEB_2_volt.setGeometry(QtCore.QRect(5, 50, 207, 31))
        font = QtGui.QFont()
        font.setBold(False)
        self.lcdFEB_2_volt.setFont(font)
        self.lcdFEB_2_volt.setAutoFillBackground(True)
        self.lcdFEB_2_volt.setStyleSheet("")
        self.lcdFEB_2_volt.setObjectName("lcdFEB_2_volt")
        self.lcdFEB_2_curr = QtWidgets.QLCDNumber(self.gbCH_2)
        self.lcdFEB_2_curr.setGeometry(QtCore.QRect(5, 120, 207, 31))
        self.lcdFEB_2_curr.setDigitCount(6)
        self.lcdFEB_2_curr.setObjectName("lcdFEB_2_curr")
        self.lblFEB_V2 = QtWidgets.QLabel(self.gbCH_2)
        self.lblFEB_V2.setGeometry(QtCore.QRect(5, 30, 100, 18))
        self.lblFEB_V2.setObjectName("lblFEB_V2")
        self.lblFEB_A2 = QtWidgets.QLabel(self.gbCH_2)
        self.lblFEB_A2.setGeometry(QtCore.QRect(5, 100, 100, 18))
        self.lblFEB_A2.setObjectName("lblFEB_A2")
        self.pbCH_2 = QtWidgets.QToolButton(self.gbCH_2)
        self.pbCH_2.setGeometry(QtCore.QRect(10, 170, 201, 30))
        self.pbCH_2.setStatusTip("")
        self.pbCH_2.setCheckable(True)
        self.pbCH_2.setObjectName("pbCH_2")
        self.horizontalLayout.addWidget(self.gbCH_2)

        self.retranslateUi(frHMP)
        QtCore.QMetaObject.connectSlotsByName(frHMP)

    def retranslateUi(self, frHMP):
        _translate = QtCore.QCoreApplication.translate
        frHMP.setWindowTitle(_translate("frHMP", "Frame"))
        self.gbCH_1.setTitle(_translate("frHMP", "CH 1"))
        self.lblFEB_V1.setText(_translate("frHMP", "Voltage"))
        self.lblFEB_A1.setText(_translate("frHMP", "Current"))
        self.pbCH_1.setText(_translate("frHMP", "ON/OFF"))
        self.gbCH_2.setTitle(_translate("frHMP", "CH 2"))
        self.lblFEB_V2.setText(_translate("frHMP", "Voltage"))
        self.lblFEB_A2.setText(_translate("frHMP", "Current"))
        self.pbCH_2.setText(_translate("frHMP", "ON/OFF"))
