# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_comments.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(380, 205)
        self.pteComment = QtWidgets.QPlainTextEdit(Frame)
        self.pteComment.setGeometry(QtCore.QRect(5, 50, 370, 150))
        self.pteComment.setObjectName("pteComment")
        self.qlProject_2 = QtWidgets.QLabel(Frame)
        self.qlProject_2.setGeometry(QtCore.QRect(5, 30, 200, 25))
        self.qlProject_2.setAutoFillBackground(False)
        self.qlProject_2.setObjectName("qlProject_2")
        self.pbOperator = QtWidgets.QPushButton(Frame)
        self.pbOperator.setGeometry(QtCore.QRect(5, 5, 370, 30))
        self.pbOperator.setObjectName("pbOperator")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.qlProject_2.setText(_translate("Frame", "Comment"))
        self.pbOperator.setText(_translate("Frame", "Operator"))
