# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_EMU_CONTROL.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EMU_CONTROL(object):
    def setupUi(self, EMU_CONTROL):
        EMU_CONTROL.setObjectName("EMU_CONTROL")
        EMU_CONTROL.resize(450, 210)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EMU_CONTROL.sizePolicy().hasHeightForWidth())
        EMU_CONTROL.setSizePolicy(sizePolicy)
        EMU_CONTROL.setMinimumSize(QtCore.QSize(450, 210))
        EMU_CONTROL.setMaximumSize(QtCore.QSize(450, 210))
        self.centralwidget = QtWidgets.QWidget(EMU_CONTROL)
        self.centralwidget.setObjectName("centralwidget")
        self.wdgPOWER = QtWidgets.QWidget(self.centralwidget)
        self.wdgPOWER.setGeometry(QtCore.QRect(0, 80, 450, 100))
        self.wdgPOWER.setObjectName("wdgPOWER")
        self.pbControlHub = QtWidgets.QToolButton(self.centralwidget)
        self.pbControlHub.setGeometry(QtCore.QRect(10, 10, 151, 66))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbControlHub.sizePolicy().hasHeightForWidth())
        self.pbControlHub.setSizePolicy(sizePolicy)
        self.pbControlHub.setToolTip("")
        self.pbControlHub.setStatusTip("")
        self.pbControlHub.setWhatsThis("")
        self.pbControlHub.setAccessibleName("")
        self.pbControlHub.setAccessibleDescription("")
        self.pbControlHub.setAutoFillBackground(True)
        self.pbControlHub.setObjectName("pbControlHub")
        self.pbConnect2EMU = QtWidgets.QToolButton(self.centralwidget)
        self.pbConnect2EMU.setGeometry(QtCore.QRect(170, 10, 151, 67))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbConnect2EMU.sizePolicy().hasHeightForWidth())
        self.pbConnect2EMU.setSizePolicy(sizePolicy)
        self.pbConnect2EMU.setToolTip("")
        self.pbConnect2EMU.setStatusTip("")
        self.pbConnect2EMU.setWhatsThis("")
        self.pbConnect2EMU.setAccessibleName("")
        self.pbConnect2EMU.setAccessibleDescription("")
        self.pbConnect2EMU.setObjectName("pbConnect2EMU")
        self.pbRead = QtWidgets.QToolButton(self.centralwidget)
        self.pbRead.setGeometry(QtCore.QRect(330, 10, 110, 67))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbRead.sizePolicy().hasHeightForWidth())
        self.pbRead.setSizePolicy(sizePolicy)
        self.pbRead.setToolTip("")
        self.pbRead.setStatusTip("")
        self.pbRead.setWhatsThis("")
        self.pbRead.setAccessibleName("")
        self.pbRead.setAccessibleDescription("")
        self.pbRead.setObjectName("pbRead")
        EMU_CONTROL.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(EMU_CONTROL)
        self.statusbar.setObjectName("statusbar")
        EMU_CONTROL.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(EMU_CONTROL)
        self.actionAbout.setObjectName("actionAbout")
        self.actionWeb_manual = QtWidgets.QAction(EMU_CONTROL)
        self.actionWeb_manual.setObjectName("actionWeb_manual")
        self.actionConnect = QtWidgets.QAction(EMU_CONTROL)
        self.actionConnect.setObjectName("actionConnect")
        self.actionDisconnect = QtWidgets.QAction(EMU_CONTROL)
        self.actionDisconnect.setObjectName("actionDisconnect")

        self.retranslateUi(EMU_CONTROL)
        QtCore.QMetaObject.connectSlotsByName(EMU_CONTROL)

    def retranslateUi(self, EMU_CONTROL):
        _translate = QtCore.QCoreApplication.translate
        EMU_CONTROL.setWindowTitle(_translate("EMU_CONTROL", "Module Tester Power Supply"))
        self.pbControlHub.setText(_translate("EMU_CONTROL", "Controlhub"))
        self.pbConnect2EMU.setText(_translate("EMU_CONTROL", "Connect 2 EMU"))
        self.pbRead.setText(_translate("EMU_CONTROL", "Read"))
        self.actionAbout.setText(_translate("EMU_CONTROL", "About"))
        self.actionWeb_manual.setText(_translate("EMU_CONTROL", "Web manual"))
        self.actionConnect.setText(_translate("EMU_CONTROL", "Connect"))
        self.actionDisconnect.setText(_translate("EMU_CONTROL", "Disconnect"))
