# Form implementation generated from reading ui file 'sfp_control.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SfpControl(object):
    def setupUi(self, SfpControl):
        SfpControl.setObjectName("SfpControl")
        SfpControl.resize(393, 58)
        self.layoutWidget = QtWidgets.QWidget(parent=SfpControl)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 371, 39))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cob_sfp = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.cob_sfp.setObjectName("cob_sfp")
        self.cob_sfp.addItem("")
        self.cob_sfp.addItem("")
        self.cob_sfp.addItem("")
        self.cob_sfp.addItem("")
        self.cob_sfp.addItem("")
        self.horizontalLayout.addWidget(self.cob_sfp)
        self.line = QtWidgets.QFrame(parent=self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.cob_dev = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.cob_dev.setObjectName("cob_dev")
        self.cob_dev.addItem("")
        self.cob_dev.addItem("")
        self.horizontalLayout.addWidget(self.cob_dev)

        self.retranslateUi(SfpControl)
        QtCore.QMetaObject.connectSlotsByName(SfpControl)

    def retranslateUi(self, SfpControl):
        _translate = QtCore.QCoreApplication.translate
        SfpControl.setWindowTitle(_translate("SfpControl", "Form"))
        self.cob_sfp.setItemText(0, _translate("SfpControl", "SFP 0"))
        self.cob_sfp.setItemText(1, _translate("SfpControl", "SFP 1"))
        self.cob_sfp.setItemText(2, _translate("SfpControl", "SFP 2"))
        self.cob_sfp.setItemText(3, _translate("SfpControl", "SFP 3"))
        self.cob_sfp.setItemText(4, _translate("SfpControl", "SFP All"))
        self.cob_dev.setItemText(0, _translate("SfpControl", "DEV 0"))
        self.cob_dev.setItemText(1, _translate("SfpControl", "DEV ALL"))
