# Form implementation generated from reading ui file 'tamex_channel.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TamexChannel(object):
    def setupUi(self, TamexChannel):
        TamexChannel.setObjectName("TamexChannel")
        TamexChannel.resize(393, 53)
        self.layoutWidget = QtWidgets.QWidget(parent=TamexChannel)
        self.layoutWidget.setGeometry(QtCore.QRect(5, 10, 381, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_ch = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_ch.setFont(font)
        self.lbl_ch.setObjectName("lbl_ch")
        self.horizontalLayout.addWidget(self.lbl_ch)
        self.isb_dac = QtWidgets.QSpinBox(parent=self.layoutWidget)
        self.isb_dac.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.isb_dac.setMaximum(1023)
        self.isb_dac.setProperty("value", 0)
        self.isb_dac.setObjectName("isb_dac")
        self.horizontalLayout.addWidget(self.isb_dac)
        self.hsb_dac = QtWidgets.QSlider(parent=self.layoutWidget)
        self.hsb_dac.setMaximum(1023)
        self.hsb_dac.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.hsb_dac.setObjectName("hsb_dac")
        self.horizontalLayout.addWidget(self.hsb_dac)
        self.dsb_mV = QtWidgets.QDoubleSpinBox(parent=self.layoutWidget)
        self.dsb_mV.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.dsb_mV.setMaximum(1000.0)
        self.dsb_mV.setObjectName("dsb_mV")
        self.horizontalLayout.addWidget(self.dsb_mV)

        self.retranslateUi(TamexChannel)
        QtCore.QMetaObject.connectSlotsByName(TamexChannel)

    def retranslateUi(self, TamexChannel):
        _translate = QtCore.QCoreApplication.translate
        TamexChannel.setWindowTitle(_translate("TamexChannel", "Form"))
        self.lbl_ch.setText(_translate("TamexChannel", "CH 1"))
