# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tamex_channel.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TamexChannel(object):
    def setupUi(self, TamexChannel):
        TamexChannel.setObjectName("TamexChannel")
        TamexChannel.resize(393, 53)
        self.widget = QtWidgets.QWidget(TamexChannel)
        self.widget.setGeometry(QtCore.QRect(5, 10, 381, 31))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_ch = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_ch.setFont(font)
        self.lbl_ch.setObjectName("lbl_ch")
        self.horizontalLayout.addWidget(self.lbl_ch)
        self.sb_dac = QtWidgets.QSpinBox(self.widget)
        self.sb_dac.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_dac.setMaximum(1023)
        self.sb_dac.setProperty("value", 1023)
        self.sb_dac.setObjectName("sb_dac")
        self.horizontalLayout.addWidget(self.sb_dac)
        self.isb_dac = QtWidgets.QSlider(self.widget)
        self.isb_dac.setOrientation(QtCore.Qt.Horizontal)
        self.isb_dac.setObjectName("isb_dac")
        self.horizontalLayout.addWidget(self.isb_dac)
        self.dsb_mV = QtWidgets.QDoubleSpinBox(self.widget)
        self.dsb_mV.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_mV.setMaximum(1000.0)
        self.dsb_mV.setObjectName("dsb_mV")
        self.horizontalLayout.addWidget(self.dsb_mV)

        self.retranslateUi(TamexChannel)
        QtCore.QMetaObject.connectSlotsByName(TamexChannel)

    def retranslateUi(self, TamexChannel):
        _translate = QtCore.QCoreApplication.translate
        TamexChannel.setWindowTitle(_translate("TamexChannel", "Form"))
        self.lbl_ch.setText(_translate("TamexChannel", "CH 1"))
