## List of nodes
## comment line starts with # and is ignored; empty lines are also ignored
## format: node_name 'directory'
x86l-170 'TimeSorter'
x86l-260 'FMF1_MUSIC'
x86l-132 'FMF2_PLSCI'
x86l-261 'FHF1_MUSIC'
x86l-253 'FHF1_SCIFI3'
#raspi4 'Raspberry Pi 4'
