## List of nodes
## comment line starts with # and is ignored; empty lines are also ignored
## format: node_name 'description'
com 'COM - Communication Node'
mbs 'MBS - Multi Node Control System'
web 'Web Interface'
