## List of nodes
## comment line starts with # and is ignored; empty lines are also ignored
## format: node_name 'description'
## keep sequence of nodes the same as in list_of_nodes.conf
com 'COM - Communication Node'
web 'MBS - Web Interface'
mbs 'MBS - Multi Node Control System'
